"$schema" = 'https://starship.rs/config-schema.json'

palette = "miku"
format = """
[](color_user)\
$os\
$username\
[](bg:color_pwd fg:color_user)\
$directory\
[](fg:color_pwd bg:color_git)\
$git_branch\
$git_status\
[](fg:color_git bg:color_lang)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:color_lang bg:color_docker)\
$docker_context\
[](fg:color_docker bg:color_time)\
$time\
[ ](fg:color_time)\n$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:color_user fg:color_fg_user"
style_root = "bg:color_user fg:color_fg_user"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:color_user fg:color_fg"
disabled = true # Disabled by default

[directory]
style = "bg:color_pwd fg:color_fg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:color_docker fg:color_fg"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:color_git fg:color_fg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_git fg:color_fg"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:color_lang fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color_time fg:color_fg"
format = '[ ♥ $time ]($style)'


[palettes.charlotte]
color_user = '#aaf5fc'
color_pwd = '#aac4fc'
color_git = '#c1aafc'
color_lang = '#f3aafc'
color_docker = '#fcb1aa'
color_time = '#fce2aa'
color_fg = '#1c1f24'
color_fg_user = '#1c1f24'
color_ok = '#B9F3FC'
color_error = '#FEDEFF'

[palettes.default]
color_user = '#9A348E'
color_pwd = '#DA627D'
color_git = '#FCA17D'
color_lang = '#86BBD8'
color_docker = '#06969A'
color_time = '#33658A'
color_fg = '#ffffff'
color_fg_user = '#ffffff'
color_ok = '#B9F3FC'
color_error = '#FEDEFF'

[palettes.dark_charlotte]
color_user = '#80bcbd'
color_pwd = '#8097bd'
color_git = '#a580bd'
color_lang = '#bd80bd'
color_docker = '#bd8c80'
color_time = '#bda580'
color_fg = '#1c1f24'
color_fg_user = '#1c1f24'
color_ok = '#B9F3FC'
color_error = '#FEDEFF'

[palettes.reorder]
color_user = '#33658A'
color_pwd = '#06969A'
color_git = '#86BBD8'
color_lang = '#FCA17D'
color_docker = '#DA627D'
color_time = '#9A348E'
color_fg = '#fbf1c7'
color_fg_user = '#F9F9E0'
color_ok = '#B9F3FC'
color_error = '#FEDEFF'

[palettes.miku]
color_user = '#ef86bb'
color_pwd = '#FEDEFF'
color_git = '#F9F9E0'
color_lang = '#93C6E7'
color_docker ='#b0eaff' # '#A6DDF2'
color_time = '#B9F3FC'
color_fg = '#33658A'
color_fg_user = '#F9F9E0'
color_ok = '#B9F3FC'
color_error = '#ef86bb'



[character]
disabled = false
success_symbol = '[>](bold fg:color_ok)'
error_symbol = '[>](bold fg:color_error)'
